CREATE TABLE Setor(
cods INTEGER	 	PRIMARY KEY 	NOT NULL,
nome VARCHAR(20)	 NOT NULL
);

CREATE TABLE Mecanico(
codm INTEGER	 	PRIMARY KEY 	NOT NULL,
cpf CHAR(11)		NOT NULL,
nome VARCHAR(20)	 NOT NULL,
idade INTEGER		NOT NULL,
endereco VARCHAR(40),
cidade VARCHAR(20),
funcao VARCHAR(20),
cods INTEGER,
FOREIGN KEY (cods) REFERENCES Setor
);


CREATE TABLE Cliente(
codc INTEGER PRIMARY KEY NOT NULL,
cpf CHAR(11) NOT NULL,
nome VARCHAR(30) NOT NULL,
idade INTEGER,
endereco VARCHAR(30),
cidade VARCHAR(20)
);

CREATE TABLE Veiculo(
codv INTEGER	 	PRIMARY KEY 	NOT NULL,
renavam INTEGER		NOT NULL,
modelo 	VARCHAR(20)	 NOT NULL,
marca	 VARCHAR (10)	NOT NULL,
ano	INTEGER		NOT NULL,
quilometragem INTEGER	NOT NULL,
codc INTEGER NOT NULL,
FOREIGN KEY (codc) REFERENCES Cliente
);


CREATE TABLE Conserto(
codm INTEGER NOT NULL,
codv INTEGER NOT NULL,
data DATE PRIMARY KEY NOT NULL,
hora TIME NOT NULL,
FOREIGN KEY (codm) REFERENCES Mecanico,
FOREIGN KEY (codv) REFERENCES Veiculo
);
